name: Basic PR Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-basic-check:
    name: Run Basic Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a simple test
        run: echo "基础检查通过！"